      - name: Send final IPA to Telegram bot
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BOT_CHAT_ID: ${{ secrets.TELEGRAM_BOT_CHAT_ID }}

          APP_NAME: ${{ steps.prepare.outputs.app_name }}
          BUNDLE_ID: ${{ steps.prepare.outputs.bundle_id }}
          APP_VERSION: ${{ steps.prepare.outputs.version }}
          ADDON_NAME: ${{ steps.prepare.outputs.addon_name }}

        run: |
          python telegram_send.py
